name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        -
            name: Build
            run: cargo build --release -p mica-cli
        -
            name: Run Language and API tests
            run: cargo test --release -- --include-ignored

    clippy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        -
            name: Clippy
            run: cargo clippy

    rustfmt:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        -
            name: rustfmt
            run: cargo fmt --check --all
